
2019-07-28 00:45:22,096 INFO: errors [in E:\testing\New folder\flask-boilerplate-master\app.py:207]
2019-07-28 00:45:23,938 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:207]
2019-07-28 00:48:02,658 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:207]
2019-07-28 00:49:02,193 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:207]
2019-07-28 00:49:21,955 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:207]
2019-07-28 00:50:11,718 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:207]
2019-07-28 02:39:55,858 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:207]
2019-07-28 02:39:59,428 ERROR: Exception on /result [POST] [in C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:/testing/New folder/flask-boilerplate-master/app.py", line 142, in get_result
    cluster_n = np.int16(request.values['cohorts'])
ValueError: invalid literal for int() with base 10: ''
2019-07-28 02:42:39,720 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:207]
2019-07-30 13:32:42,341 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:207]
2019-07-30 13:35:39,076 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:207]
2019-07-30 21:11:34,246 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:207]
2019-07-30 21:18:30,660 ERROR: Exception on /result [POST] [in C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:/testing/New folder/flask-boilerplate-master/app.py", line 142, in get_result
    cluster_n = np.int16(request.values['cohorts'])
ValueError: invalid literal for int() with base 10: ''
2019-07-30 21:18:32,853 ERROR: Exception on /result [POST] [in C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:/testing/New folder/flask-boilerplate-master/app.py", line 142, in get_result
    cluster_n = np.int16(request.values['cohorts'])
ValueError: invalid literal for int() with base 10: ''
2019-07-30 21:18:34,025 ERROR: Exception on /result [POST] [in C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:/testing/New folder/flask-boilerplate-master/app.py", line 142, in get_result
    cluster_n = np.int16(request.values['cohorts'])
ValueError: invalid literal for int() with base 10: ''
2019-07-30 21:18:35,252 ERROR: Exception on /result [POST] [in C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:/testing/New folder/flask-boilerplate-master/app.py", line 142, in get_result
    cluster_n = np.int16(request.values['cohorts'])
ValueError: invalid literal for int() with base 10: ''
2019-07-30 21:18:36,451 ERROR: Exception on /result [POST] [in C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:/testing/New folder/flask-boilerplate-master/app.py", line 142, in get_result
    cluster_n = np.int16(request.values['cohorts'])
ValueError: invalid literal for int() with base 10: ''
2019-07-30 21:18:38,021 ERROR: Exception on /result [POST] [in C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:/testing/New folder/flask-boilerplate-master/app.py", line 142, in get_result
    cluster_n = np.int16(request.values['cohorts'])
ValueError: invalid literal for int() with base 10: ''
2019-07-30 21:18:43,067 ERROR: Exception on /result [POST] [in C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:/testing/New folder/flask-boilerplate-master/app.py", line 142, in get_result
    cluster_n = np.int16(request.values['cohorts'])
ValueError: invalid literal for int() with base 10: ''
2019-07-30 21:18:44,338 ERROR: Exception on /result [POST] [in C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:/testing/New folder/flask-boilerplate-master/app.py", line 142, in get_result
    cluster_n = np.int16(request.values['cohorts'])
ValueError: invalid literal for int() with base 10: ''
2019-07-30 21:18:45,506 ERROR: Exception on /result [POST] [in C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:/testing/New folder/flask-boilerplate-master/app.py", line 142, in get_result
    cluster_n = np.int16(request.values['cohorts'])
ValueError: invalid literal for int() with base 10: ''
2019-07-30 21:18:47,577 ERROR: Exception on /result [POST] [in C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:/testing/New folder/flask-boilerplate-master/app.py", line 142, in get_result
    cluster_n = np.int16(request.values['cohorts'])
ValueError: invalid literal for int() with base 10: ''
2019-07-30 21:18:49,242 ERROR: Exception on /result [POST] [in C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:/testing/New folder/flask-boilerplate-master/app.py", line 142, in get_result
    cluster_n = np.int16(request.values['cohorts'])
ValueError: invalid literal for int() with base 10: ''
2019-07-30 21:26:42,307 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:207]
2019-07-30 21:30:16,305 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:207]
2019-07-30 21:36:38,757 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:207]
2019-07-30 21:37:56,184 ERROR: Exception on /result [POST] [in C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:/testing/New folder/flask-boilerplate-master/app.py", line 178, in get_result
    m_str += '<tr data-toggle="modal" data-target="#myModal" class="cluster-row" id="' + n + '">'
TypeError: can only concatenate str (not "int") to str
2019-07-30 21:43:21,194 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:207]
2019-07-30 21:43:36,379 ERROR: Exception on /result [POST] [in C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:/testing/New folder/flask-boilerplate-master/app.py", line 178, in get_result
    m_str += '<tr data-toggle="modal" data-target="#myModal" class="cluster-row" id="' + n + '">'
TypeError: can only concatenate str (not "int") to str
2019-07-30 21:43:51,720 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:207]
2019-07-30 21:44:01,307 ERROR: Exception on /result [POST] [in C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:/testing/New folder/flask-boilerplate-master/app.py", line 178, in get_result
    m_str += '<tr data-toggle="modal" data-target="#myModal" class="cluster-row" id="' + n + '">'
TypeError: can only concatenate str (not "int") to str
2019-07-30 21:44:23,702 ERROR: Exception on /result [POST] [in C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:/testing/New folder/flask-boilerplate-master/app.py", line 178, in get_result
    m_str += '<tr data-toggle="modal" data-target="#myModal" class="cluster-row" id="' + n + '">'
TypeError: can only concatenate str (not "int") to str
2019-07-30 21:45:41,647 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:207]
2019-07-30 21:45:54,473 ERROR: Exception on /result [POST] [in C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:/testing/New folder/flask-boilerplate-master/app.py", line 178, in get_result
    m_str += '<tr data-toggle="modal" data-target="#myModal" class="cluster-row" id="' + n + '">'
TypeError: can only concatenate str (not "int") to str
2019-07-30 21:47:25,929 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:207]
2019-07-30 21:48:27,439 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:207]
2019-07-30 21:49:41,460 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:207]
2019-07-30 21:53:09,421 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:207]
2019-07-30 21:55:32,086 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:207]
2019-07-30 21:56:35,494 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:207]
2019-07-30 21:57:41,852 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:207]
2019-07-30 21:58:00,370 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:207]
2019-07-30 21:58:52,641 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:207]
2019-08-02 02:21:02,409 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:258]
2019-08-02 02:26:09,229 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:263]
2019-08-02 02:28:02,050 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:263]
2019-08-02 02:28:14,103 ERROR: Exception on /result [POST] [in C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:/testing/New folder/flask-boilerplate-master/app.py", line 155, in get_result
    le.fit(data1[m_category_name].values)
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
2019-08-02 02:29:02,185 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:263]
2019-08-02 02:30:48,531 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:263]
2019-08-02 02:41:17,412 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 02:42:50,221 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 02:44:54,556 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 02:50:52,449 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 02:53:02,681 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 04:51:50,772 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 04:52:16,020 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 04:52:55,586 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 04:53:36,888 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 04:53:51,286 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 04:54:03,478 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 04:56:59,777 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 04:59:17,222 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 04:59:49,089 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 05:00:23,748 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 05:00:56,070 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 05:02:28,284 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 05:03:32,715 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 05:03:54,828 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 05:04:10,922 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 05:07:45,687 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 05:08:31,329 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 05:10:01,541 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 05:10:27,578 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 05:16:17,545 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 15:38:25,696 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 15:43:28,733 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 22:13:56,360 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 22:15:23,970 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 22:18:52,284 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 22:34:20,684 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 22:36:54,769 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:265]
2019-08-02 22:43:08,435 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:266]
2019-08-02 22:43:37,998 ERROR: Exception on /result [POST] [in C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1993, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\wrappers\base_response.py", line 269, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\wrappers\base_response.py", line 26, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\test.py", line 1119, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'dict' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1835, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1850, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2001, in make_response
    reraise(TypeError, new_error, sys.exc_info()[2])
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1993, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\wrappers\base_response.py", line 269, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\wrappers\base_response.py", line 26, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\test.py", line 1119, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'dict' object is not callable
The view function did not return a valid response. The return type must be a string, tuple, Response instance, or WSGI callable, but it was a dict.
2019-08-02 22:44:38,536 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:266]
2019-08-02 22:44:53,740 ERROR: Exception on /result [POST] [in C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:/testing/New folder/flask-boilerplate-master/app.py", line 193, in get_result
    return jsonify({"table": m_str, "data": C})
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 351, in jsonify
    dumps(data, indent=indent, separators=separators) + '\n',
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 194, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 81, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Users\Elite\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
2019-08-02 22:45:21,270 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:266]
2019-08-02 22:46:42,700 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:267]
2019-08-02 22:48:31,539 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:267]
2019-08-02 22:49:50,050 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:267]
2019-08-02 22:51:57,511 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:267]
2019-08-02 22:57:42,330 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:270]
2019-08-02 22:58:39,791 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:270]
2019-08-02 22:59:37,434 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:270]
2019-08-02 23:01:59,068 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:270]
2019-08-02 23:05:29,563 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:272]
2019-08-02 23:06:05,820 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:272]
2019-08-02 23:06:27,354 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:272]
2019-08-02 23:07:18,263 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:272]
2019-08-02 23:08:12,993 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:272]
2019-08-02 23:13:43,474 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:279]
2019-08-02 23:15:10,320 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:279]
2019-08-02 23:16:52,580 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:279]
2019-08-02 23:21:59,174 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:279]
2019-08-02 23:37:40,633 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:279]
2019-08-02 23:38:53,338 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:279]
2019-08-04 01:17:42,463 INFO: errors [in E:/testing/New folder/flask-boilerplate-master/app.py:258]
